repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: python
        entry: flake8
        additional_dependencies:
          - flake8-builtins
          - flake8-print
          - flake8-quotes